email:
  false

dist:
  trusty

git:
  depth:
    false

env:
  global:
    - secure: "BzKU/o+j0ga5sT7ufQLN1lkBiTlAQIqZVZgJP6cIRaFEMVw6B5toHF5Nyzn4Td+phXAp6gBIGUIh9W4P6j6kPkiBpwF9wGh39HK9+lrYaxTkbhp1287jveCFP5tozKBxLQa7yy1uSQdQLjL2cIWQy7eCqhx711+HpSlOk0ozVrP3yt+cVP2YHE7lGBuy+g+B8kb7zgHLSGcRzN735AmJJYm4XGHHqWIZyWem+Iv1/GWg47VoUuzj+/vIQLaZ6EM2T/3VhxNDDDYu01YZssLQb4c6jVKwQCADnI4JVkRNDCdEjJZ0+8qQOCUV3sWFUUMAY5sH+9rue5Y2v/TAGmsrmRgEto3z31vrrdiAMBSScFgMcDaaAcTxKZZDRtzrjf9gVXr1ujfCQJcSAG18zDrV4LNJ+Gdj6ARGs+E3/PvmqMnU2pJ4+8iYjDtksDXuXWXVZT+5dD8UE+wN65jZW7dWSrN7JsyNdxTGj83di60jLkYeLXjNxKZ1PZxRzcDAggQ/BIIQfMloTApYqW2iDeSMt/me7mO/JRnJmYqS1mn3S1/2xck/N/yWuyR9bQ1M7Atyuzjp3D7DzdhJnBQBxQsEYjtpW1KhVtV6LxcONalBgA8+ILzkBAfxpt1Q3FDjctOByX3SWsm9VPNxP6I57QlGMn6NqvNDRMsOnl8e7jN4bkk="

cache:
  bundler

language:
  ruby

rvm:
  - 2.3.8
  - 2.4.6
  - 2.5.5
  - 2.6.3

before_install:
  - gem install bundler

script:
  - bundle exec rake coverage

