email:
  false

dist:
  trusty

git:
  depth:
    false

env:
  global:
    - secure: "QHXOR4XS9Scn+YGs554WLVRhl1/8Xm6J8edE3rItyz9YARtrTcYV5C3MhQPW0kbu/27rPgd3BbGnwKozz4EVGBZlJlBWxgf8d/bx4InSHdYvnNAxTFyfe7tNS3ePWSfgPSsD5+dZMjSDZdLYKwcIkpVzeTf48fbQ5NvjvrNfq2RXzptP50RqV7sYz7m4rrgXUBsiAMyrg6jyz8i4jt9Pk/7lkNfwFcGhXadqts0qT5k4vJaqf9kby6M5gtGgR5Fua3TAEvVhq/LkXxa2nh3B1acpJ1sWc3HYADNYebweGMaF4YInpRJh/Aj4GtcBPofYdSG4+uP70dXL2ZWnii3bYQ5HeBKYmLc1FKq62aPnIwcL/cSmRfM9ab8mYEx4s2r/O7SJJTXkWHb9jNj8quIjfe3jqmVvAQedH9Y1fFCJDqtEw0xc5qb1e5c9Pv0ZSuYKfUii1dsGTXZ4QN+iT0cdH3i0XYLjEwOVYfOElbO5Anee4cj1krzICW4CPzmQcrmlzqbQfOLbkAjQY5oyQ9CrWkRF5iJW2jmnszZ13NwSbCMHz/R5Yiz1xGWGDZRTdvE5NJfTKQjUxzEV6qZeRAT+0xmwzhtjJ7qyh6Coi+cyd8WXc6JvRaTU0oIEbiCvaWJnBpWRJ2cTp3S70C7FoFcCFYUelSDSiJ9/PxyPJrW8pu4="

cache:
  bundler

language:
  ruby

rvm:
  - 2.3.8
  - 2.4.6
  - 2.5.5
  - 2.6.3

before_install:
  - gem install bundler

script:
  - bundle exec rake coverage
